export const industries = [
  "Công nghệ thông tin",
  "Giáo dục",
  "Y tế",
  "Tài chính",
  "Xây dựng",
  "Marketing",
  "Luật",
  "Nông nghiệp",
  "Vận tải",
  "Du lịch",
  "Bất động sản",
  "Thương mại điện tử",
  "Sản xuất",
  "Dịch vụ khách hàng",
  "Kỹ thuật",
  "Năng lượng",
  "Hóa chất",
  "Thực phẩm và đồ uống",
  "Dược phẩm",
  "Viễn thông",
  "Logistics",
  "Bảo hiểm",
];
